version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "80:80"

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: E-commerce
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
